// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dragonslayer_api.Models;

#nullable disable

namespace dragonslayer_api.Migrations
{
    [DbContext(typeof(DragonslayerGameContext))]
    [Migration("20240530192820_AddGametTextTable")]
    partial class AddGametTextTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dragonslayer_api.Models.Attack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttackText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attack_text");

                    b.Property<int>("CharacterClassId")
                        .HasColumnType("integer")
                        .HasColumnName("character_class_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DisplayId")
                        .HasColumnType("integer")
                        .HasColumnName("display_id");

                    b.Property<int>("ManaCost")
                        .HasColumnType("integer")
                        .HasColumnName("mana_cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<int>("Power")
                        .HasColumnType("integer")
                        .HasColumnName("power");

                    b.HasKey("Id")
                        .HasName("attack_pkey");

                    b.HasIndex(new[] { "CharacterClassId", "DisplayId" }, "attack_character_class_id_display_id_key")
                        .IsUnique();

                    b.ToTable("attack", (string)null);
                });

            modelBuilder.Entity("dragonslayer_api.Models.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DenialText")
                        .HasColumnType("text")
                        .HasColumnName("denial_text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("character_class_pkey");

                    b.ToTable("character_class", (string)null);
                });

            modelBuilder.Entity("dragonslayer_api.Models.ExtraEffect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttackId")
                        .HasColumnType("integer")
                        .HasColumnName("attack_id");

                    b.Property<int?>("AttackToBeReplacedBy")
                        .HasColumnType("integer")
                        .HasColumnName("attack_to_be_replaced_by");

                    b.Property<decimal?>("EffectMultiplier")
                        .HasColumnType("numeric")
                        .HasColumnName("effect_multiplier");

                    b.Property<string>("SpecialText")
                        .HasColumnType("text")
                        .HasColumnName("special_text");

                    b.Property<string>("TargetCharacter")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("target_character");

                    b.Property<string>("TargetStat")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("target_stat");

                    b.Property<int?>("TurnsLost")
                        .HasColumnType("integer")
                        .HasColumnName("turns_lost");

                    b.HasKey("Id")
                        .HasName("extra_effect_pkey");

                    b.HasIndex("AttackId");

                    b.ToTable("extra_effect", (string)null);
                });

            modelBuilder.Entity("dragonslayer_api.Models.GameText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBadEndText")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bad_end_text");

                    b.Property<bool>("IsFlavorText")
                        .HasColumnType("boolean")
                        .HasColumnName("is_flavor_text");

                    b.Property<bool>("IsGoodEndText")
                        .HasColumnType("boolean")
                        .HasColumnName("is_good_end_text");

                    b.Property<bool>("IsNarrativeText")
                        .HasColumnType("boolean")
                        .HasColumnName("is_narrative_text");

                    b.Property<bool>("IsStartText")
                        .HasColumnType("boolean")
                        .HasColumnName("is_start_text");

                    b.Property<string>("TextContent")
                        .HasColumnType("text")
                        .HasColumnName("text_content");

                    b.HasKey("Id")
                        .HasName("game_text_pkey");

                    b.ToTable("GameText");
                });

            modelBuilder.Entity("dragonslayer_api.Models.Stat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Attack")
                        .HasColumnType("integer")
                        .HasColumnName("attack");

                    b.Property<int>("CharacterClassId")
                        .HasColumnType("integer")
                        .HasColumnName("character_class_id");

                    b.Property<int>("Defense")
                        .HasColumnType("integer")
                        .HasColumnName("defense");

                    b.Property<int>("Hp")
                        .HasColumnType("integer")
                        .HasColumnName("hp");

                    b.Property<int>("Mana")
                        .HasColumnType("integer")
                        .HasColumnName("mana");

                    b.HasKey("Id")
                        .HasName("stat_pkey");

                    b.HasIndex("CharacterClassId");

                    b.ToTable("stat", (string)null);
                });

            modelBuilder.Entity("dragonslayer_api.Models.Attack", b =>
                {
                    b.HasOne("dragonslayer_api.Models.CharacterClass", "CharacterClass")
                        .WithMany("Attacks")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("attack_character_class_id_fkey");

                    b.Navigation("CharacterClass");
                });

            modelBuilder.Entity("dragonslayer_api.Models.ExtraEffect", b =>
                {
                    b.HasOne("dragonslayer_api.Models.Attack", "Attack")
                        .WithMany("ExtraEffects")
                        .HasForeignKey("AttackId")
                        .IsRequired()
                        .HasConstraintName("extra_effect_attack_id_fkey");

                    b.Navigation("Attack");
                });

            modelBuilder.Entity("dragonslayer_api.Models.Stat", b =>
                {
                    b.HasOne("dragonslayer_api.Models.CharacterClass", "CharacterClass")
                        .WithMany("Stats")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("stat_character_class_id_fkey");

                    b.Navigation("CharacterClass");
                });

            modelBuilder.Entity("dragonslayer_api.Models.Attack", b =>
                {
                    b.Navigation("ExtraEffects");
                });

            modelBuilder.Entity("dragonslayer_api.Models.CharacterClass", b =>
                {
                    b.Navigation("Attacks");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
